### ISSUE TITLE
[Feat] 전역 에러 핸들링

### ISSUE THREAD

**Issue by stophwan** [dnd-side-project/dnd-10th-10-backend#10]
## 🧨 Description
- GlobalExceptionHandler를 구현합니다.
## 📝 To-do
- [x] Api 공통 응답 스펙 정의필요할 경우 추가 Exception 정의
- [x] RestControllerAdvice를 통한 전역 예외 핸들링
- [x] 필요할 경우 추가 Exception 정의
