### ISSUE TITLE
[Feat] 기본 Entity 생성

### ISSUE THREAD

**Issue by stophwan** [dnd-side-project/dnd-10th-10-backend#11]
## 🧨 Description
- BaseEntity를 생성합니다.
- 1차 스프린트 때 필요한 Jpa Entity를 생성합니다.

## 📝 To-do
- [x] ERD 기반으로 Entity 생성
- [x] 예약어 충돌 처리
- [x] 컬럼 이름 수정된 것 반영
- [x] 오타 수정
- [x] 앱 이름 enum으로 수정
- [x] 제한 시간 int로 수정
