### ISSUE TITLE
[Feat] 방 입장 시 중복 회원인지 체크 

### ISSUE THREAD

**Issue by jm0514** [dnd-side-project/dnd-10th-10-backend#37]
## 🧨 Description
- 방 입장 시 중복 회원인지 체크하는 로직을 추가합니다.
## 📝 To-do
- [x] 중복 회원 체크 로직 추가
- [x] 방 상태를 구분하는 Enum 추가
- [x] 방장이 방 생성시 RoomMember의 host를 true로 저장
