### ISSUE TITLE
[Feat] 방과 관련된 Swagger 작업

### ISSUE THREAD

**Issue by jm0514** [dnd-side-project/dnd-10th-10-backend#42]
## 🧨 Description
* 방과 관련된 명세를 합니다.

## 📝 To-do
- [x] 수정된 API 수정
- [x] 참여방 조회 명세
- [x] 방 상세 조회(대기방) 명세
- [x] 방 삭제 명세
- [x] 호스트 확인 명세
